In [1]:
import numpy as np


In [2]:
#32. Is the following expression true?
np.sqrt(-1) == np.emath.sqrt(-1)



C:\Users\USERR\AppData\Local\Temp\ipykernel_4540\2765065376.py:2: RuntimeWarning: invalid value encountered in sqrt
  np.sqrt(-1) == np.emath.sqrt(-1)


np.False_

In [5]:
#33. getting dates of yesterday today and tommorrow
yesterday = np.datetime64('today') -np.timedelta64(1)
today = np.datetime64('today')
tommorrow = np.datetime64('today') + np.timedelta64(1)

print(yesterday,today,tommorrow)


2024-09-18 2024-09-19 2024-09-20


In [7]:
#34
Z = np.arange('2016-07','2016-08',dtype='datetime64[D]')
print(Z)


['2016-07-01' '2016-07-02' '2016-07-03' '2016-07-04' '2016-07-05'
 '2016-07-06' '2016-07-07' '2016-07-08' '2016-07-09' '2016-07-10'
 '2016-07-11' '2016-07-12' '2016-07-13' '2016-07-14' '2016-07-15'
 '2016-07-16' '2016-07-17' '2016-07-18' '2016-07-19' '2016-07-20'
 '2016-07-21' '2016-07-22' '2016-07-23' '2016-07-24' '2016-07-25'
 '2016-07-26' '2016-07-27' '2016-07-28' '2016-07-29' '2016-07-30'
 '2016-07-31']


In [36]:
#36
n = np.random.uniform(0,5,5)

print(np.floor(n))
print(n // 1)
print(np.trunc(n))
print(n.astype(int))


[0. 4. 2. 1. 0.]
[0. 4. 2. 1. 0.]
[0. 4. 2. 1. 0.]
[0 4 2 1 0]


In [53]:
#37
x = np.tile(np.arange(0,5),(5,1))
x

array([[0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4]])

In [56]:
#38
def generate():
    for y in range(10):
        yield y
m = np.fromiter(generate(),dtype=float,count=-1)
print(m)


[0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]


In [64]:
#39
y = np.linspace(0,1,12,endpoint=True)[1:-1]
print(y)


[0.09090909 0.18181818 0.27272727 0.36363636 0.45454545 0.54545455
 0.63636364 0.72727273 0.81818182 0.90909091]


In [69]:
#40
x = np.random.random(10)
print("Original array: ")
print(x)
x.sort()
print("Sorted array: ")
print(x)




Original array: 
[0.83943375 0.75968104 0.88180412 0.04861292 0.43319499 0.77605009
 0.01735126 0.46414189 0.3290959  0.55234285]
Sorted array: 
[0.01735126 0.04861292 0.3290959  0.43319499 0.46414189 0.55234285
 0.75968104 0.77605009 0.83943375 0.88180412]


In [71]:
#41
x = np.arange(10)
np.add.reduce(x)


np.int64(45)

In [73]:
#42
A = np.random.randint(0,3,5)
B = np.random.randint(0,3,5)
equal = np.array_equal(A,B)
print(equal)


False


In [74]:
#43
x = np.zeros(10)
x.flags.writeable = False
x[0] = 1


ValueError: assignment destination is read-only

In [76]:
#44
m = np.random.random((10,2))
X,Y = m[:0],m[:,1]
R = np.sqrt(X**2+Y**2)
T = np.arctan2(Y,X)
print(R)
print(T)



ValueError: operands could not be broadcast together with shapes (0,2) (10,) 

In [79]:
#45
x = np.random.random(10)
x[x.argmax()]=0
print(x)


[0.08549021 0.86953242 0.27141918 0.02237645 0.82299254 0.07034515
 0.68110544 0.16165114 0.         0.86044134]
